package dto

const (
	// 2xx Success
	STATUS_OK         = 200
	STATUS_CREATED    = 201
	STATUS_ACCEPTED   = 202
	STATUS_NO_CONTENT = 204

	// 3xx Redirection
	STATUS_MOVED_PERMANENTLY = 301
	STATUS_FOUND             = 302
	STATUS_NOT_MODIFIED      = 304

	// 4xx Client Errors
	STATUS_BAD_REQUEST          = 400
	STATUS_UNAUTHORIZED         = 401
	STATUS_FORBIDDEN            = 403
	STATUS_NOT_FOUND            = 404
	STATUS_METHOD_NOT_ALLOWED   = 405
	STATUS_CONFLICT             = 409
	STATUS_UNPROCESSABLE_ENTITY = 422
	STATUS_TOO_MANY_REQUESTS    = 429

	// 5xx Server Errors
	STATUS_INTERNAL_SERVER_ERROR = 500
	STATUS_NOT_IMPLEMENTED       = 501
	STATUS_BAD_GATEWAY           = 502
	STATUS_SERVICE_UNAVAILABLE   = 503
)
