INSERT INTO films (id, judul, status, sinopsis, durasi, total_episode, sutradara, tanggal_rili) VALUES
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f01','Harry Potter and the Philosopher''s Stone','finished airing','Harry Potter, seorang anak yatim piatu yang dibesarkan oleh keluarga Dursley yang kejam, hidup tanpa mengetahui jati dirinya yang sebenarnya. Pada ulang tahunnya yang kesebelas, ia mengetahui bahwa dirinya adalah seorang penyihir terkenal di dunia sihir. Harry kemudian memasuki Hogwarts School of Witchcraft and Wizardry, tempat ia mempelajari sihir, menjalin persahabatan dengan Ron Weasley dan Hermione Granger, serta mulai mengungkap misteri tentang kematian orang tuanya. Di balik keajaiban Hogwarts, tersembunyi ancaman besar yang menguji keberanian dan takdir Harry sejak langkah pertamanya di dunia sihir.',152,1,'Chris Columbus','2001-11-16'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f02','The Lord of the Rings: The Fellowship of the Ring','finished airing','Di dunia Middle-earth yang penuh legenda, sebuah cincin kuno dengan kekuatan luar biasa kembali muncul dan mengancam keseimbangan dunia. Frodo Baggins, seorang hobbit sederhana, mewarisi cincin tersebut tanpa menyadari bahaya besar yang mengikutinya. Bersama para sahabat dari berbagai ras—manusia, elf, dwarf, dan penyihir—Frodo membentuk sebuah persekutuan untuk menghancurkan cincin itu di Gunung Doom. Perjalanan mereka dipenuhi pengkhianatan, pengorbanan, dan ujian persahabatan, menandai awal dari peperangan besar antara kebaikan dan kejahatan.',178,1,'Peter Jackson','2001-12-19'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f03','The Dark Knight','finished airing','Batman menghadapi ujian terberatnya ketika seorang kriminal jenius bernama Joker muncul dan menebar kekacauan di Gotham City. Joker tidak menginginkan kekayaan atau kekuasaan, melainkan kehancuran moral dan mental para pahlawan. Di tengah konflik antara hukum, keadilan, dan kekacauan, Bruce Wayne harus mempertanyakan batasan yang ia tetapkan sebagai Batman. Film ini menggambarkan pertarungan psikologis yang intens serta pengorbanan besar demi melindungi kota dari kehancuran total.',152,1,'Christopher Nolan','2008-07-18'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f04','Inception','finished airing','Dom Cobb adalah seorang pencuri profesional yang memiliki kemampuan langka untuk memasuki alam bawah sadar seseorang melalui mimpi dan mencuri rahasia terdalam mereka. Ia ditawari sebuah kesempatan untuk menebus masa lalunya dengan melakukan misi yang hampir mustahil: menanamkan sebuah ide ke dalam pikiran targetnya. Bersama tim spesialis, Cobb menjelajahi lapisan mimpi yang semakin dalam, di mana batas antara realitas dan ilusi menjadi kabur. Setiap keputusan membawa risiko kegagalan yang dapat menjebak mereka selamanya di dunia mimpi.',148,1,'Christopher Nolan','2010-07-16'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f05','Interstellar','finished airing','Ketika bumi menghadapi kehancuran akibat krisis lingkungan dan kelangkaan sumber daya, seorang mantan pilot NASA bernama Cooper direkrut untuk menjalankan misi berbahaya melintasi luar angkasa. Dengan memanfaatkan lubang cacing, Cooper dan timnya mencari planet baru yang layak dihuni umat manusia. Perjalanan ini tidak hanya menguji batas ilmu pengetahuan dan waktu, tetapi juga hubungan emosional antara ayah dan anak. Interstellar menyajikan kisah tentang pengorbanan, cinta, dan harapan umat manusia di tengah ketidakpastian kosmik.',169,1,'Christopher Nolan','2014-11-07'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f06','Avengers: Infinity War','finished airing','Para Avengers dan sekutunya harus bersatu menghadapi ancaman terbesar yang pernah mereka hadapi: Thanos, seorang Titan dengan ambisi untuk menyeimbangkan alam semesta dengan cara memusnahkan setengah dari seluruh kehidupan. Dengan mengumpulkan Infinity Stones yang memiliki kekuatan tak terbatas, Thanos bergerak tanpa ampun. Pertempuran berlangsung di berbagai penjuru galaksi, memaksa para pahlawan untuk mengorbankan segalanya demi mencegah kehancuran total. Film ini dipenuhi konflik emosional dan momen krusial yang mengubah masa depan semesta Marvel.',149,1,'Anthony Russo, Joe Russo','2018-04-27'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f07','Avengers: Endgame','finished airing','Setelah kekalahan besar akibat jentikan jari Thanos, dunia berada dalam kondisi porak-poranda. Para Avengers yang tersisa harus menghadapi kehilangan, rasa bersalah, dan keputusasaan. Dengan satu kesempatan terakhir, mereka merancang rencana berbahaya untuk mengubah takdir dan mengembalikan mereka yang telah hilang. Endgame menjadi penutup epik dari perjalanan panjang para pahlawan, menampilkan pengorbanan terbesar, perpisahan emosional, dan makna sejati dari kepahlawanan.',181,1,'Anthony Russo, Joe Russo','2019-04-26'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f08','Titanic','finished airing','Di atas kapal mewah RMS Titanic yang dianggap tak dapat tenggelam, terjalin kisah cinta antara Jack Dawson, seorang seniman miskin, dan Rose DeWitt Bukater, wanita bangsawan yang terjebak dalam kehidupan yang mengekang. Hubungan mereka tumbuh di tengah perbedaan kelas sosial yang tajam. Namun, ketika bencana besar terjadi dan kapal menabrak gunung es, cinta dan keberanian diuji di tengah tragedi yang mengguncang sejarah. Titanic menggabungkan romansa mendalam dengan kisah nyata tentang kehilangan dan harapan.',195,1,'James Cameron','1997-12-19'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f09','Jurassic Park','finished airing','Sebuah taman hiburan revolusioner yang menghadirkan dinosaurus hidup hasil rekayasa genetika menjadi mimpi yang berubah menjadi mimpi buruk. Ketika sistem keamanan gagal, para ilmuwan dan pengunjung harus bertahan hidup dari makhluk prasejarah yang lepas kendali. Jurassic Park tidak hanya menyajikan ketegangan dan aksi, tetapi juga mempertanyakan batas etika manusia dalam memanipulasi alam. Film ini menjadi tonggak penting dalam sejarah perfilman modern.',127,1,'Steven Spielberg','1993-06-11'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f0a','The Matrix','finished airing','Thomas Anderson, seorang programmer yang juga dikenal sebagai hacker bernama Neo, menemukan bahwa dunia yang ia kenal hanyalah sebuah simulasi buatan. Ia direkrut oleh kelompok pemberontak untuk melawan sistem cerdas yang memperbudak umat manusia. Saat Neo mulai memahami perannya sebagai penyelamat, ia harus menghadapi pilihan sulit antara kenyamanan ilusi dan kebebasan yang menyakitkan. The Matrix menyajikan aksi futuristik sekaligus refleksi filosofis tentang realitas dan identitas.',136,1,'The Wachowskis','1999-03-31'),
-- ==================================================
-- MOVIES (BARAT / INTERNASIONAL) - ID 0b s/d 14
-- ==================================================

('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f0b', 'The Shawshank Redemption', 'finished airing', 'Andy Dufresne, seorang bankir sukses, dijatuhi hukuman penjara seumur hidup atas pembunuhan istri dan selingkuhannya, kejahatan yang ia klaim tidak ia lakukan. Di Penjara Shawshank yang brutal, ia berteman dengan Red, seorang penyelundup barang, dan perlahan mendapatkan rasa hormat dari para narapidana serta penjaga melalui integritas, harapan, dan keahlian akuntansinya yang tak ternilai, sambil merencanakan jalan menuju kebebasan sejati.', 142, 1, 'Frank Darabont', '1994-09-22'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f0c', 'The Godfather', 'finished airing', 'Kisah epik tentang keluarga kriminal Corleone di New York pasca-perang. Don Vito Corleone, sang patriark yang bijaksana namun berbahaya, berusaha mentransfer kekuasaannya kepada putranya yang enggan, Michael. Namun, serangkaian peristiwa tragis dan serangan dari keluarga mafia saingan memaksa Michael untuk meninggalkan idealismenya dan terjun ke dalam dunia kejahatan yang penuh darah, akhirnya bertransformasi menjadi bos mafia yang lebih kejam dari ayahnya.', 175, 1, 'Francis Ford Coppola', '1972-03-24'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f0d', 'Pulp Fiction', 'finished airing', 'Sebuah narasi non-linear yang menjalin kisah hidup dua pembunuh bayaran yang filosofis, seorang petinju yang menolak menjatuhkan diri dalam pertandingan, istri seorang gangster yang kecanduan narkoba, dan sepasang perampok restoran. Kehidupan mereka bertabrakan dalam serangkaian insiden kekerasan yang aneh, dialog ikonik, dan humor gelap di dunia kriminal Los Angeles.', 154, 1, 'Quentin Tarantino', '1994-10-14'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f0e', 'Parasite', 'finished airing', 'Keluarga Kim yang miskin namun cerdik perlahan menyusup ke dalam kehidupan keluarga Park yang kaya raya dengan menyamar sebagai pekerja profesional yang tidak saling mengenal. Hubungan simbiosis parasitisme ini berjalan lancar hingga sebuah insiden tak terduga di ruang bawah tanah rumah mewah tersebut mengancam untuk menghancurkan segalanya, memicu konflik kelas sosial yang brutal dan tak terelakkan.', 132, 1, 'Bong Joon-ho', '2019-05-30'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f0f', 'Fight Club', 'finished airing', 'Seorang pekerja kantor yang menderita insomnia kronis dan merasa kosong dengan kehidupan materialistisnya bertemu dengan Tyler Durden, seorang pembuat sabun yang karismatik dan anarkis. Bersama-sama, mereka membentuk klub pertarungan bawah tanah sebagai pelampiasan agresi pria modern. Namun, klub tersebut berkembang menjadi gerakan teroris anti-kapitalis yang berbahaya, memaksa sang narator untuk menghadapi kebenaran mengejutkan tentang identitas Tyler.', 139, 1, 'David Fincher', '1999-10-15'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f10', 'Forrest Gump', 'finished airing', 'Forrest Gump, seorang pria dengan IQ rendah namun berhati emas, secara tidak sengaja menjadi saksi dan peserta dalam beberapa peristiwa paling bersejarah di Amerika Serikat pada abad ke-20, mulai dari Perang Vietnam hingga skandal Watergate. Di tengah perjalanan hidupnya yang luar biasa, satu-satunya hal yang ia inginkan adalah bersatu kembali dengan cinta masa kecilnya, Jenny, yang hidupnya penuh dengan gejolak.', 142, 1, 'Robert Zemeckis', '1994-07-06'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f11', 'Whiplash', 'finished airing', 'Andrew Neiman, seorang drummer jazz muda yang ambisius, mendaftar di konservatorium musik elit di mana ia bertemu dengan Terence Fletcher, seorang instruktur yang menggunakan metode pengajaran yang kasar, manipulatif, dan melecehkan secara mental demi "mendorong" siswanya mencapai kesempurnaan. Andrew didorong ke ambang kewarasan dan kehancuran fisik dalam upayanya untuk mendapatkan pengakuan dari mentornya yang tirani.', 106, 1, 'Damien Chazelle', '2014-10-10'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f12', 'Everything Everywhere All At Once', 'finished airing', 'Seorang imigran Tionghoa-Amerika yang kelelahan, Evelyn Wang, terseret dalam petualangan gila melintasi multiverse. Ia harus menghubungkan kesadarannya dengan versi dirinya dari alam semesta lain untuk mendapatkan kekuatan demi menyelamatkan dunia dari ancaman entitas jahat, yang ternyata memiliki hubungan sangat pribadi dan menyakitkan dengan keluarganya sendiri.', 139, 1, 'Daniels', '2022-03-25'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f13', 'Mad Max: Fury Road', 'finished airing', 'Di dunia pasca-apokaliptik yang tandus di mana air dan bensin adalah komoditas langka, Max Rockatansky bergabung dengan Imperator Furiosa yang mengkhianati pemimpin tiran Immortan Joe. Mereka melarikan diri melintasi gurun dengan truk perang raksasa, membawa lima istri Joe yang diperbudak, dikejar oleh pasukan fanatik dalam pertempuran jalanan yang tak henti-henti dan visual yang memukau.', 120, 1, 'George Miller', '2015-05-15'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f14', 'Oppenheimer', 'finished airing', 'Biopik epik yang menyelami jiwa J. Robert Oppenheimer, fisikawan teoretis yang memimpin Proyek Manhattan. Film ini mengeksplorasi kecemerlangan ilmiahnya, dilema moral yang menghantuinya saat menciptakan bom atom pertama, serta intrik politik pasca-perang yang berusaha menghancurkan karier dan reputasinya sebagai "Bapak Bom Atom".', 180, 1, 'Christopher Nolan', '2023-07-21'),

-- ==================================================
-- WESTERN SERIES (SERIAL BARAT) - ID 15 s/d 1e
-- ==================================================

('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f15', 'Breaking Bad', 'finished airing', 'Walter White, seorang guru kimia yang santun namun frustrasi, mendapati hidupnya hancur ketika didiagnosis kanker paru-paru stadium akhir. Putus asa untuk mengamankan masa depan finansial keluarganya, ia bekerja sama dengan mantan muridnya, Jesse Pinkman, untuk memproduksi metamfetamin biru murni. Perjalanannya mengubahnya dari pria biasa menjadi raja narkoba yang menakutkan bernama "Heisenberg".', 50, 62, 'Vince Gilligan', '2008-01-20'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f16', 'Game of Thrones', 'finished airing', 'Sembilan keluarga bangsawan bertempur habis-habisan demi menguasai tanah mitos Westeros, sementara musuh kuno bangkit kembali setelah tertidur selama ribuan tahun di balik tembok es raksasa di Utara. Penuh dengan intrik politik, pengkhianatan, naga, dan sihir, perebutan Iron Throne memakan banyak korban jiwa dan mengubah takdir benua tersebut selamanya.', 60, 73, 'David Benioff', '2011-04-17'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f17', 'Stranger Things', 'airing', 'Di kota kecil Hawkins tahun 1980-an, hilangnya seorang anak laki-laki secara misterius memicu serangkaian peristiwa aneh yang melibatkan eksperimen rahasia pemerintah, kekuatan supranatural yang menakutkan, dan seorang gadis kecil aneh bernama Eleven. Sekelompok anak-anak harus menghadapi monster dari dimensi paralel yang disebut "The Upside Down" demi menyelamatkan teman dan kota mereka.', 55, 34, 'Duffer Brothers', '2016-07-15'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f18', 'The Last of Us', 'airing', 'Dua puluh tahun setelah peradaban modern dihancurkan oleh wabah jamur yang mengubah manusia menjadi monster kanibal, Joel, seorang penyelundup yang keras hati, disewa untuk membawa Ellie, gadis berusia 14 tahun, keluar dari zona karantina. Apa yang dimulai sebagai pekerjaan kecil berubah menjadi perjalanan brutal dan memilukan melintasi Amerika Serikat, di mana mereka harus bergantung satu sama lain untuk bertahan hidup.', 55, 9, 'Craig Mazin', '2023-01-15'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f19', 'Black Mirror', 'airing', 'Serial antologi yang mengeksplorasi sisi gelap masyarakat modern dan ketakutan kolektif terhadap teknologi. Setiap episode berdiri sendiri dengan latar belakang distopia yang terasa sangat dekat dengan realitas kita, menyoroti bagaimana ketergantungan manusia pada layar, media sosial, dan kecerdasan buatan dapat memanipulasi perilaku dan menghancurkan kemanusiaan.', 60, 27, 'Charlie Brooker', '2011-12-04'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f1a', 'Chernobyl', 'finished airing', 'Dramatisasi mendalam tentang bencana nuklir tahun 1986 di Uni Soviet, salah satu bencana buatan manusia terburuk dalam sejarah. Serial ini menyoroti kisah para pahlawan tak dikenal yang mengorbankan nyawa mereka untuk membersihkan dampak radiasi, serta kebohongan sistemik dan birokrasi yang menyebabkan tragedi tersebut dan upaya pemerintah untuk menutupinya.', 60, 5, 'Johan Renck', '2019-05-06'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f1b', 'The Boys', 'airing', 'Di dunia di mana pahlawan super ("Supes") dipuja bak selebriti namun sebenarnya korup, egois, dan sosiopat, sekelompok vigilante yang disebut "The Boys" berusaha mengungkap kebenaran tentang "The Seven", tim pahlawan super terkuat, dan Vought International, konglomerat bernilai miliaran dolar yang mengelola dan menutupi kejahatan mereka.', 60, 24, 'Eric Kripke', '2019-07-26'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f1c', 'Succession', 'finished airing', 'Kisah keluarga Roy, pemilik konglomerat media global Waystar Royco. Ketika sang patriark, Logan Roy, mulai mengalami masalah kesehatan, keempat anaknya yang disfungsional terlibat dalam perebutan kekuasaan yang kejam, penuh pengkhianatan, dan manipulasi untuk menentukan siapa yang akan mewarisi takhta perusahaan raksasa tersebut.', 60, 39, 'Jesse Armstrong', '2018-06-03'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f1d', 'Peaky Blinders', 'finished airing', 'Berlatar di Birmingham, Inggris, pasca-Perang Dunia I, serial ini mengikuti kebangkitan keluarga kriminal Shelby. Dipimpin oleh Tommy Shelby yang ambisius dan kejam, geng Peaky Blinders menjahit silet di topi mereka dan berjuang memperluas kekuasaan bisnis ilegal mereka, menghadapi ancaman dari polisi, IRA, hingga fasisme yang sedang berkembang.', 60, 36, 'Steven Knight', '2013-09-12'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f1e', 'The Queen''s Gambit', 'finished airing', 'Beth Harmon, seorang anak yatim piatu di tahun 1950-an, menemukan bakat luar biasa dalam permainan catur. Sambil berjuang melawan kecanduan obat penenang dan alkohol yang menghantuinya sejak kecil, ia meniti karier di dunia catur profesional yang didominasi pria, bertekad untuk menjadi grandmaster terbaik di dunia.', 60, 7, 'Scott Frank', '2020-10-23'),

-- ==================================================
-- K-DRAMA (DRAKOR) - ID 1f s/d 28
-- ==================================================

('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f1f', 'Squid Game', 'airing', 'Ratusan orang yang terlilit utang parah menerima undangan misterius untuk bertanding dalam permainan anak-anak tradisional Korea. Hadiahnya sangat menggiurkan, 45,6 miliar won, tetapi konsekuensi kekalahannya adalah kematian. Para peserta harus menghadapi dilema moral dan insting bertahan hidup yang brutal di arena permainan yang berdarah.', 55, 9, 'Hwang Dong-hyuk', '2021-09-17'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f20', 'Crash Landing on You', 'finished airing', 'Yoon Se-ri, seorang pewaris konglomerat Korea Selatan, mendarat darurat di Korea Utara akibat kecelakaan paralayang. Ia ditemukan oleh Ri Jeong-hyeok, seorang perwira tentara Korea Utara yang kaku namun berhati hangat. Jeong-hyeok memutuskan untuk menyembunyikan dan melindunginya, dan di tengah ketegangan politik kedua negara, benih-benih cinta mulai tumbuh di antara mereka.', 70, 16, 'Lee Jeong-hyo', '2019-12-14'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f21', 'Reply 1988', 'finished airing', 'Drama nostalgia yang menghangatkan hati tentang kehidupan lima keluarga yang tinggal bertetangga di lingkungan Ssangmun-dong, Seoul, pada tahun 1988. Serial ini menyoroti persahabatan lima remaja yang tumbuh bersama, cinta pertama, dinamika keluarga yang rumit, serta budaya pop Korea di masa itu, memberikan potret kehidupan yang autentik dan emosional.', 90, 20, 'Shin Won-ho', '2015-11-06'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f22', 'Kingdom', 'finished airing', 'Di era Joseon, rumor tentang raja yang sakit parah mencengkeram kerajaan, sementara wabah misterius mulai menyebar, mengubah manusia menjadi monster pemakan daging di malam hari. Putra Mahkota Lee Chang harus menghadapi tuduhan pengkhianatan sambil berjuang menyelamatkan rakyatnya dari wabah zombie dan intrik politik istana yang korup.', 50, 12, 'Kim Seong-hun', '2019-01-25'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f23', 'The Glory', 'finished airing', 'Seorang wanita yang hidupnya hancur akibat kekerasan sekolah yang brutal di masa remajanya mendedikasikan hidupnya untuk merancang balas dendam yang rumit. Ia menjadi guru wali kelas bagi anak dari penyiksanya, dan perlahan-lahan menjatuhkan para pelaku serta orang-orang yang membiarkan kekerasan itu terjadi, satu per satu tanpa ampun.', 50, 16, 'Ahn Gil-ho', '2022-12-30'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f24', 'Goblin: The Lonely and Great God', 'finished airing', 'Kim Shin, seorang jenderal abadi dari Dinasti Goryeo, dikutuk untuk hidup selamanya menyaksikan kematian orang-orang yang dicintainya. Ia mencari pengantin manusia yang dinubuatkan dapat mencabut pedang tak kasat mata dari dadanya dan mengakhiri keabadiannya. Takdir mempertemukannya dengan seorang siswa SMA yang ceria yang mengaku sebagai pengantinnya.', 75, 16, 'Lee Eung-bok', '2016-12-02'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f25', 'Descendants of the Sun', 'finished airing', 'Kisah cinta yang intens antara Kapten Yoo Shi-jin, pemimpin pasukan khusus penjaga perdamaian, dan Dokter Kang Mo-yeon, seorang ahli bedah yang berdedikasi. Mereka ditugaskan bersama di negara fiksi Uruk yang dilanda perang, di mana keyakinan mereka yang bertentangan tentang nilai kehidupan diuji di tengah situasi berbahaya, bencana alam, dan ancaman epidemi.', 60, 16, 'Lee Eung-bok', '2016-02-24'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f26', 'Hospital Playlist', 'finished airing', 'Mengisahkan kehidupan sehari-hari yang luar biasa dari lima dokter spesialis yang telah bersahabat sejak sekolah kedokteran tahun 1999. Bekerja di rumah sakit yang sama, mereka menghadapi kelahiran, kematian, dan segala sesuatu di antaranya dengan pasien mereka, sambil menyempatkan diri untuk bermain band bersama di akhir pekan.', 80, 24, 'Shin Won-ho', '2020-03-12'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f27', 'Moving', 'finished airing', 'Tiga remaja sekolah menengah yang tampak biasa menyembunyikan kekuatan super luar biasa yang mereka warisi dari orang tua mereka. Sementara mereka mencoba menavigasi masa remaja, orang tua mereka yang merupakan mantan agen rahasia berjuang mati-matian untuk melindungi anak-anak mereka dari kekuatan gelap pemerintah yang ingin memanfaatkan bakat mereka.', 60, 20, 'Park In-je', '2023-08-09'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f28', 'All of Us Are Dead', 'airing', 'Wabah virus zombie pecah di sebuah sekolah menengah di Korea Selatan, menjebak para siswa di dalamnya tanpa akses ke makanan atau komunikasi. Para siswa yang tersisa harus menggunakan peralatan sekolah seadanya untuk melawan teman-teman mereka yang telah berubah menjadi monster dan bertahan hidup hingga bantuan datang.', 60, 12, 'Lee Jae-kyoo', '2022-01-28'),

-- ==================================================
-- ANIME SERIES & MOVIES - ID 29 s/d 32
-- ==================================================

('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f29', 'Attack on Titan', 'finished airing', 'Umat manusia hidup di balik tembok raksasa untuk melindungi diri dari Titan, raksasa humanoid pemakan manusia. Setelah kampung halamannya dihancurkan dan ibunya dimakan, Eren Yeager bersumpah untuk membasmi seluruh Titan. Namun, seiring berjalannya waktu, ia mengungkap konspirasi gelap tentang asal-usul Titan, sejarah dunia yang terhapus, dan musuh sebenarnya yang berada di seberang lautan.', 24, 89, 'Tetsuro Araki', '2013-04-07'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f2a', 'Fullmetal Alchemist: Brotherhood', 'finished airing', 'Dua bersaudara, Edward dan Alphonse Elric, melanggar hukum tabu alkimia saat mencoba menghidupkan kembali ibu mereka yang sudah meninggal, mengakibatkan hilangnya tubuh fisik mereka. Mereka memulai perjalanan mencari Philosopher''s Stone untuk memulihkan tubuh mereka, namun malah terseret dalam konspirasi nasional yang melibatkan homunculus buatan dan rencana jahat yang mengancam seluruh negeri Amestris.', 24, 64, 'Yasuhiro Irie', '2009-04-05'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f2b', 'Death Note', 'finished airing', 'Light Yagami, seorang siswa jenius, menemukan buku catatan supranatural milik Shinigami yang dapat membunuh siapa saja yang namanya tertulis di dalamnya. Dengan nama samaran "Kira", ia memulai misinya untuk membersihkan dunia dari kejahatan dan menjadi dewa dunia baru, namun rencananya ditantang oleh detektif eksentrik bernama L dalam pertempuran kecerdasan kucing-tikus yang menegangkan.', 23, 37, 'Tetsuro Araki', '2006-10-03'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f2c', 'One Piece', 'airing', 'Monkey D. Luffy, seorang pemuda yang tubuhnya memiliki sifat karet setelah memakan Buah Iblis, berlayar melintasi Grand Line bersama kru bajak laut Topi Jerami yang beragam. Tujuan utamanya adalah menemukan harta karun legendaris "One Piece" yang ditinggalkan oleh Raja Bajak Laut sebelumnya, Gol D. Roger, dan menjadi Raja Bajak Laut baru di dunia yang didominasi lautan.', 24, 1080, 'Eiichiro Oda', '1999-10-20'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f2d', 'Jujutsu Kaisen', 'airing', 'Yuji Itadori, seorang siswa SMA dengan kekuatan fisik luar biasa, menelan jari terkutuk milik iblis legendaris Ryomen Sukuna demi menyelamatkan teman-temannya. Kini berbagi tubuh dengan Sukuna, Yuji bergabung dengan Sekolah Jujutsu Tokyo untuk belajar mengendalikan energi kutukan dan memburu sisa jari Sukuna sebelum ia dieksekusi oleh organisasi penyihir.', 24, 47, 'Sunghoo Park', '2020-10-03'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f2e', 'Cyberpunk: Edgerunners', 'finished airing', 'Di kota distopia Night City yang terobsesi dengan teknologi dan modifikasi tubuh, David Martinez, seorang anak jalanan yang kehilangan segalanya, memilih untuk bertahan hidup dengan menjadi Edgerunner—seorang tentara bayaran kriminal yang juga dikenal sebagai cyberpunk. Ia bergabung dengan kru peretas dan penembak jitu, namun ambisi dan kecanduan sibernetik membawanya ke jalan kehancuran.', 25, 10, 'Hiroyuki Imaishi', '2022-09-13'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f2f', 'Naruto Shippuden', 'finished airing', 'Melanjutkan perjalanan Naruto Uzumaki setelah dua setengah tahun pelatihan intensif. Naruto kembali ke Desa Konoha dengan kekuatan baru dan tekad yang lebih kuat untuk menyelamatkan temannya, Sasuke Uchiha, yang telah jatuh ke dalam kegelapan, sambil menghadapi ancaman organisasi kriminal Akatsuki yang memburu Jinchuriki (wadah monster berekor) untuk tujuan dominasi dunia.', 23, 500, 'Hayato Date', '2007-02-15'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f30', 'Vinland Saga', 'airing', 'Thorfinn, putra dari salah satu pejuang Viking terhebat, menghabiskan masa mudanya di medan perang sebagai bagian dari kru tentara bayaran yang dipimpin oleh Askeladd, pria yang membunuh ayahnya. Didorong oleh rasa dendam dan keinginan untuk berduel dengan Askeladd, Thorfinn terseret dalam perang perebutan mahkota Inggris, mempertanyakan arti kehormatan, kekerasan, dan tanah damai bernama Vinland.', 24, 48, 'Shuhei Yabuta', '2019-07-07'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f31', 'Violet Evergarden', 'finished airing', 'Setelah perang besar berakhir, Violet, seorang mantan prajurit anak yang hanya tahu cara membunuh dan tidak memiliki emosi, memulai hidup baru sebagai "Auto Memory Doll"—penulis surat profesional. Melalui pekerjaan menuliskan perasaan orang lain ke dalam kata-kata, ia perlahan mulai memahami emosi manusia dan makna di balik kata-kata terakhir yang diucapkan mayornya kepadanya: "Aku mencintaimu".', 24, 13, 'Taichi Ishidate', '2018-01-11'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f32', 'Chainsaw Man', 'finished airing', 'Denji, seorang pemuda miskin yang bekerja sebagai pemburu iblis demi melunasi utang ayahnya, dikhianati dan dibunuh. Ia dihidupkan kembali oleh anjing iblis peliharaannya, Pochita, dan menjadi hibrida manusia-gergaji mesin. Direkrut oleh Keamanan Publik, Denji bertarung melawan iblis-iblis mengerikan hanya demi mewujudkan mimpi-mimpi sederhananya seperti makan roti selai dan menyentuh wanita.', 24, 12, 'Ryu Nakayama', '2022-10-12'),

-- ==================================================
-- CULT CLASSICS & CRIME (33 - 3c)
-- ==================================================

('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f33', 'Goodfellas', 'finished airing', 'Kisah nyata Henry Hill dan kehidupannya di dalam mafia, mencakup hubungannya dengan istrinya Karen dan rekan-rekannya Jimmy Conway dan Tommy DeVito dalam sindikat kejahatan Italia-Amerika. Film ini menggambarkan kemewahan dan kebrutalan kehidupan gangster selama tiga dekade.', 146, 1, 'Martin Scorsese', '1990-09-19'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f34', 'The Silence of the Lambs', 'finished airing', 'Clarice Starling, seorang peserta pelatihan FBI muda, harus meminta bantuan dr. Hannibal Lecter, seorang psikiater jenius sekaligus pembunuh kanibal yang dipenjara, untuk menangkap pembunuh berantai lain yang dikenal sebagai "Buffalo Bill" yang menguliti korbannya.', 118, 1, 'Jonathan Demme', '1991-02-14'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f35', 'Se7en', 'finished airing', 'Dua detektif, satu veteran yang hampir pensiun dan satu pemula yang idealis, memburu seorang pembunuh berantai yang menggunakan tujuh dosa mematikan (kerakusan, keserakahan, kemalasan, kemurkaan, hawa nafsu, iri hati, dan kesombongan) sebagai motif dalam pembunuhan-pembunuhan sadisnya.', 127, 1, 'David Fincher', '1995-09-22'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f36', 'The Usual Suspects', 'finished airing', 'Seorang penipu kecil yang selamat dari pembantaian di sebuah kapal menceritakan kisah berbelit-belit kepada polisi tentang bagaimana ia dan empat penjahat lainnya dipertemukan oleh sosok kriminal legendaris yang misterius dan menakutkan bernama Keyser Söze.', 106, 1, 'Bryan Singer', '1995-08-16'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f37', 'Scarface', 'finished airing', 'Tony Montana, seorang imigran Kuba di Miami tahun 1980, mengambil alih kartel narkoba dengan kekerasan dan kekejaman, hingga akhirnya menyerah pada keserakahan dan paranoia yang menghancurkan kerajaan kokain yang telah ia bangun.', 170, 1, 'Brian De Palma', '1983-12-09'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f38', 'Reservoir Dogs', 'finished airing', 'Setelah perampokan perhiasan yang sederhana menjadi kacau balau, para perampok yang selamat mulai mencurigai bahwa salah satu dari mereka adalah informan polisi, memicu ketegangan psikologis dan kekerasan berdarah di sebuah gudang kosong.', 99, 1, 'Quentin Tarantino', '1992-09-02'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f39', 'No Country for Old Men', 'finished airing', 'Kekerasan dan kekacauan terjadi setelah seorang pemburu menemukan hasil transaksi narkoba yang gagal dan uang tunai dua juta dolar di dekat Rio Grande. Ia dikejar oleh seorang pembunuh psikopat, Anton Chigurh, yang memutuskan nasib korbannya dengan lemparan koin.', 122, 1, 'Coen Brothers', '2007-11-21'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f3a', 'City of God', 'finished airing', 'Di daerah kumuh Rio de Janeiro, jalur kehidupan dua anak menyimpang; satu berjuang untuk menjadi fotografer, sementara yang lain menjadi gembong narkoba yang ambisius dan kejam. Film ini menggambarkan pertumbuhan kejahatan terorganisir di pinggiran kota Brasil.', 130, 1, 'Fernando Meirelles', '2002-08-30'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f3b', 'Taxi Driver', 'finished airing', 'Travis Bickle, seorang veteran Perang Vietnam yang tidak stabil secara mental, bekerja sebagai sopir taksi malam di New York City. Muak dengan dekadensi dan kekotoran kota, ia memicu kekerasan dalam upaya menyimpang untuk menyelamatkan seorang pelacur di bawah umur.', 114, 1, 'Martin Scorsese', '1976-02-08'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f3c', 'The Departed', 'finished airing', 'Polisi menyusupkan mata-mata ke dalam geng mafia Irlandia di Boston, sementara mafia juga memiliki mata-mata di kepolisian. Ketika kedua belah pihak menyadari situasinya, terjadi perlombaan mematikan untuk mengungkap identitas musuh sebelum mereka sendiri terungkap.', 151, 1, 'Martin Scorsese', '2006-10-06'),

-- ==================================================
-- SCI-FI & FANTASY LEGENDS (3d - 46)
-- ==================================================

('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f3d', 'Star Wars: Episode V - The Empire Strikes Back', 'finished airing', 'Setelah Rebel Alliance dikalahkan di Planet Hoth, Luke Skywalker berlatih dengan Jedi Master Yoda, sementara teman-temannya dikejar oleh Darth Vader. Luke akhirnya menghadapi Vader dalam duel lightsaber yang mengungkap kebenaran mengejutkan tentang garis keturunannya.', 124, 1, 'Irvin Kershner', '1980-05-21'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f3e', 'Back to the Future', 'finished airing', 'Marty McFly, seorang remaja tahun 80-an, secara tidak sengaja dikirim kembali ke tahun 1955 dengan mesin waktu DeLorean buatan teman ilmuwannya yang eksentrik, Doc Brown. Ia harus memastikan orang tuanya jatuh cinta agar ia tidak terhapus dari keberadaan.', 116, 1, 'Robert Zemeckis', '1985-07-03'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f3f', 'Terminator 2: Judgment Day', 'finished airing', 'Sebuah cyborg, identik dengan yang gagal membunuh Sarah Connor, kini harus melindungi putra remajanya, John Connor, dari cyborg yang lebih maju dan mematikan, T-1000. Bersama-sama mereka mencoba mencegah kiamat nuklir yang dikenal sebagai Judgment Day.', 137, 1, 'James Cameron', '1991-07-03'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f40', 'Alien', 'finished airing', 'Awak kapal tunda komersial Nostromo merespons panggilan darurat dari bulan yang tidak dikenal. Mereka menemukan bentuk kehidupan mematikan yang berkembang biak di dalam inang manusia, memaksa kru untuk berjuang bertahan hidup di ruang angkasa yang sunyi.', 117, 1, 'Ridley Scott', '1979-05-25'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f41', 'Blade Runner', 'finished airing', 'Di masa depan dystopia tahun 2019, Rick Deckard, seorang mantan polisi, ditugaskan untuk memburu dan "memensiunkan" empat bio-engineered androids yang dikenal sebagai replicants yang telah mencuri kapal di luar angkasa dan kembali ke Bumi untuk mencari pencipta mereka.', 117, 1, 'Ridley Scott', '1982-06-25'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f42', 'E.T. the Extra-Terrestrial', 'finished airing', 'Seorang anak laki-laki yang kesepian berteman dengan makhluk luar angkasa yang lembut yang terdampar di Bumi. Ia dan saudara-saudaranya berusaha membantu makhluk itu pulang sambil melindunginya dari pemerintah yang ingin menangkapnya.', 115, 1, 'Steven Spielberg', '1982-06-11'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f43', 'Avatar', 'finished airing', 'Seorang marinir lumpuh dikirim ke bulan Pandora untuk misi unik: menyusup ke suku Na''vi menggunakan tubuh avatar hibrida. Namun, ia jatuh cinta pada budaya dan seorang wanita Na''vi, memaksanya memilih antara dunianya sendiri dan dunia baru yang ia cintai.', 162, 1, 'James Cameron', '2009-12-18'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f44', 'The Lord of the Rings: The Return of the King', 'finished airing', 'Gandalf dan Aragorn memimpin Dunia Manusia melawan tentara Sauron untuk mengalihkan perhatian, sementara Frodo dan Sam mendekati Gunung Doom dengan Cincin Utama. Pertempuran terakhir untuk Middle-earth dimulai, menguji kesetiaan dan keberanian semua anggota persekutuan.', 201, 1, 'Peter Jackson', '2003-12-17'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f45', 'The Truman Show', 'finished airing', 'Seorang agen asuransi yang naif menemukan bahwa seluruh hidupnya sebenarnya adalah acara TV realitas yang disiarkan 24 jam sehari ke seluruh dunia, dan semua orang di sekitarnya adalah aktor. Ia berjuang untuk melarikan diri dari dunia buatan tersebut.', 103, 1, 'Peter Weir', '1998-06-05'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f46', 'Eternal Sunshine of the Spotless Mind', 'finished airing', 'Ketika hubungannya berubah menjadi buruk, seorang wanita menjalani prosedur medis untuk menghapus mantannya dari ingatannya. Patah hati, pria itu memutuskan untuk melakukan hal yang sama, tetapi saat ia menyaksikan kenangannya memudar, ia menyadari bahwa ia masih mencintainya.', 108, 1, 'Michel Gondry', '2004-03-19'),

-- ==================================================
-- ACTION & SUPERHERO HITS (47 - 50)
-- ==================================================

('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f47', 'Die Hard', 'finished airing', 'John McClane, perwira NYPD, mencoba menyelamatkan istrinya dan beberapa orang lainnya yang disandera oleh teroris Jerman Hans Gruber selama pesta Natal di Nakatomi Plaza di Los Angeles.', 132, 1, 'John McTiernan', '1988-07-15'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f48', 'Gladiator', 'finished airing', 'Seorang jenderal Romawi yang dihormati dikhianati dan keluarganya dibunuh oleh putra kaisar yang korup. Ia datang ke Roma sebagai gladiator untuk membalas dendam dan menuntut keadilan bagi keluarganya dan kekaisaran.', 155, 1, 'Ridley Scott', '2000-05-05'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f49', 'The Avengers', 'finished airing', 'Nick Fury, direktur S.H.I.E.L.D., merekrut Tony Stark, Captain America, Hulk, dan Thor untuk membentuk tim pahlawan super guna menghentikan saudara Thor, Loki, yang berencana menaklukkan Bumi dengan pasukan alien Chitauri.', 143, 1, 'Joss Whedon', '2012-05-04'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f4a', 'Iron Man', 'finished airing', 'Setelah ditahan di gua Afghanistan, insinyur miliarder Tony Stark menciptakan baju zirah bersenjata unik untuk melawan kejahatan. Film ini adalah awal mula Marvel Cinematic Universe yang mengubah lanskap film superhero selamanya.', 126, 1, 'Jon Favreau', '2008-05-02'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f4b', 'Logan', 'finished airing', 'Di masa depan di mana mutan hampir punah, Logan yang sudah tua dan lelah merawat Profesor X yang sakit di tempat persembunyian di perbatasan Meksiko. Namun, upaya Logan untuk bersembunyi dari dunia terganggu ketika seorang mutan muda yang dikejar oleh kekuatan gelap tiba.', 137, 1, 'James Mangold', '2017-03-03'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f4c', 'Joker', 'finished airing', 'Arthur Fleck, seorang komedian gagal yang diabaikan dan dianiaya oleh masyarakat Gotham, perlahan-lahan jatuh ke dalam kegilaan dan nihilisme, bertransformasi menjadi dalang kriminal yang dikenal sebagai Joker dalam studi karakter psikologis yang gelap ini.', 122, 1, 'Todd Phillips', '2019-10-04'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f4d', 'Spider-Man', 'finished airing', 'Peter Parker, seorang siswa SMA yang canggung, digigit oleh laba-laba yang dimodifikasi secara genetik dan mendapatkan kemampuan super. Ia harus menyeimbangkan kehidupan pribadinya dengan tanggung jawab barunya melawan Green Goblin yang meneror kota.', 121, 1, 'Sam Raimi', '2002-05-03'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f4e', 'Pirates of the Caribbean: The Curse of the Black Pearl', 'finished airing', 'Pandai besi Will Turner bekerja sama dengan bajak laut eksentrik Kapten Jack Sparrow untuk menyelamatkan cintanya, putri gubernur, dari mantan sekutu Jack yang sekarang menjadi mayat hidup abadi karena kutukan emas Aztec.', 143, 1, 'Gore Verbinski', '2003-07-09'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f4f', 'Indiana Jones and the Raiders of the Lost Ark', 'finished airing', 'Arkeolog petualang Indiana Jones berlomba melawan Nazi untuk menemukan Tabut Perjanjian (Ark of the Covenant) yang legendaris, yang dikatakan memiliki kekuatan tak terkalahkan, sebelum Nazi dapat menggunakannya untuk tujuan jahat.', 115, 1, 'Steven Spielberg', '1981-06-12'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f50', 'Top Gun', 'finished airing', 'Maverick, seorang pilot tempur angkatan laut yang berbakat namun gegabah, dikirim ke sekolah Top Gun elit. Di sana ia bersaing untuk menjadi yang terbaik, jatuh cinta pada instrukturnya, dan belajar menghadapi kematian ayahnya serta sahabatnya.', 110, 1, 'Tony Scott', '1986-05-16'),

-- ==================================================
-- DRAMA & THRILLER MASTERPIECES (51 - 5a)
-- ==================================================

('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f51', 'Schindlers List', 'finished airing', 'Di Polandia yang diduduki Jerman selama Perang Dunia II, industrialis Oskar Schindler perlahan mulai khawatir akan keselamatan tenaga kerja Yahudinya setelah menyaksikan penganiayaan mereka oleh Nazi, dan mempertaruhkan kekayaannya untuk menyelamatkan lebih dari seribu orang dari Holocaust.', 195, 1, 'Steven Spielberg', '1993-12-15'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f52', 'Saving Private Ryan', 'finished airing', 'Setelah pendaratan D-Day di Normandia, Kapten John Miller membawa pasukannya di belakang garis musuh untuk menemukan Prajurit James Ryan, yang tiga saudaranya telah tewas dalam pertempuran. Misi ini menguji keberanian dan moralitas pasukan di tengah brutalnya perang.', 169, 1, 'Steven Spielberg', '1998-07-24'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f53', 'The Green Mile', 'finished airing', 'Kehidupan para penjaga di blok sel hukuman mati berubah selamanya ketika seorang narapidana kulit hitam raksasa yang dituduh membunuh dua anak, John Coffey, tiba. Ia memiliki sikap lembut dan kekuatan penyembuhan supernatural yang misterius.', 189, 1, 'Frank Darabont', '1999-12-10'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f54', 'American Beauty', 'finished airing', 'Lester Burnham, seorang ayah pinggiran kota yang mengalami krisis paruh baya dan depresi, mulai memberontak terhadap kehidupan dan keluarganya yang munafik setelah menjadi terobsesi dengan teman sahabat putrinya.', 122, 1, 'Sam Mendes', '1999-09-15'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f55', 'The Wolf of Wall Street', 'finished airing', 'Berdasarkan kisah nyata Jordan Belfort, dari kebangkitannya menjadi pialang saham kaya raya yang menjalani kehidupan pesta pora, narkoba, dan seks, hingga kejatuhannya yang tak terelakkan karena kejahatan, korupsi, dan penipuan sekuritas.', 180, 1, 'Martin Scorsese', '2013-12-25'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f56', 'Catch Me If You Can', 'finished airing', 'Kisah nyata Frank Abagnale Jr., yang sebelum ulang tahunnya yang ke-19, berhasil melakukan penipuan jutaan dolar dengan menyamar sebagai pilot Pan Am, dokter, dan pengacara. Ia terus menerus dikejar oleh agen FBI Carl Hanratty melintasi benua.', 141, 1, 'Steven Spielberg', '2002-12-25'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f57', 'Shutter Island', 'finished airing', 'Pada tahun 1954, seorang Marsekal AS menyelidiki hilangnya seorang pembunuh yang melarikan diri dari rumah sakit jiwa untuk kriminal gila di sebuah pulau terpencil. Namun, ia mulai meragukan kewarasannya sendiri seiring terungkapnya rahasia pulau tersebut.', 138, 1, 'Martin Scorsese', '2010-02-19'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f58', 'The Sixth Sense', 'finished airing', 'Seorang psikolog anak yang putus asa mencoba menebus kegagalan masa lalunya dengan membantu seorang anak laki-laki berusia delapan tahun yang mengklaim bisa melihat dan berbicara dengan orang mati, sebuah rahasia yang memiliki konsekuensi mengerikan.', 107, 1, 'M. Night Shyamalan', '1999-08-06'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f59', 'Inglourious Basterds', 'finished airing', 'Di Prancis yang diduduki Nazi, sekelompok tentara Yahudi-Amerika yang dikenal sebagai "The Basterds" dipilih untuk menyebarkan ketakutan di seluruh Reich Ketiga dengan menguliti dan membunuh Nazi secara brutal, berujung pada rencana pembunuhan para pemimpin Jerman.', 153, 1, 'Quentin Tarantino', '2009-08-21'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f5a', 'Django Unchained', 'finished airing', 'Seorang budak yang dibebaskan, Django, bekerja sama dengan pemburu hadiah Jerman untuk menyelamatkan istrinya dari pemilik perkebunan Mississippi yang brutal dan karismatik, Calvin Candie.', 165, 1, 'Quentin Tarantino', '2012-12-25'),

-- ==================================================
-- HORROR & ANIMATION CLASSICS (5b - 64)
-- ==================================================

('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f5b', 'The Shining', 'finished airing', 'Jack Torrance menjadi penjaga musim dingin di Overlook Hotel yang terisolasi di Colorado, berharap untuk menyembuhkan blok penulisnya. Namun, roh-roh jahat hotel mempengaruhinya menjadi gila dan membahayakan istri serta putranya yang memiliki kemampuan psikis.', 146, 1, 'Stanley Kubrick', '1980-05-23'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f5c', 'Psycho', 'finished airing', 'Seorang sekretaris Phoenix menggelapkan uang $40.000 dari klien bosnya, melarikan diri, dan check-in di sebuah motel terpencil yang dikelola oleh seorang pemuda yang pendiam namun aneh, Norman Bates, dan ibunya yang dominan.', 109, 1, 'Alfred Hitchcock', '1960-06-16'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f5d', 'Jaws', 'finished airing', 'Ketika seekor hiu putih besar pembunuh meneror penduduk pantai Amity Island, kepala polisi setempat, seorang ahli biologi kelautan, dan seorang pemburu hiu tua bekerja sama untuk memburunya sebelum hiu tersebut menyerang lagi.', 124, 1, 'Steven Spielberg', '1975-06-20'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f5e', 'The Lion King', 'finished airing', 'Simba, seekor anak singa pewaris tahta Pride Lands, ditipu oleh pamannya yang jahat, Scar, hingga percaya bahwa ia menyebabkan kematian ayahnya. Ia melarikan diri ke pengasingan, namun harus kembali sebagai orang dewasa untuk merebut kembali tahtanya.', 88, 1, 'Roger Allers', '1994-06-15'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f5f', 'Toy Story', 'finished airing', 'Mainan seorang anak laki-laki menjadi hidup ketika manusia tidak melihat. Woody, boneka koboi favorit, merasa terancam kedudukannya ketika mainan astronot baru yang canggih, Buzz Lightyear, datang dan merebut perhatian pemiliknya.', 81, 1, 'John Lasseter', '1995-11-22'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f60', 'Finding Nemo', 'finished airing', 'Setelah putranya ditangkap di Great Barrier Reef dan dibawa ke Sydney, seekor ikan badut yang pemalu, Marlin, melakukan perjalanan berbahaya melintasi lautan untuk membawanya pulang, ditemani oleh ikan yang pelupa bernama Dory.', 100, 1, 'Andrew Stanton', '2003-05-30'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f61', 'Shrek', 'finished airing', 'Seorang ogre yang sinis dan penyendiri bernama Shrek mendapati rawa-rawanya dibanjiri oleh makhluk dongeng yang diusir oleh Lord Farquaad. Untuk mendapatkan kembali tanahnya, ia setuju untuk menyelamatkan Putri Fiona, yang ternyata menyimpan rahasia mengejutkan.', 90, 1, 'Andrew Adamson', '2001-04-22'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f62', 'The Incredibles', 'finished airing', 'Sebuah keluarga pahlawan super yang menyamar mencoba menjalani kehidupan pinggiran kota yang tenang setelah pemerintah melarang aktivitas superhero. Namun, mereka dipaksa beraksi kembali untuk menyelamatkan dunia dari penjahat dendam bernama Syndrome.', 115, 1, 'Brad Bird', '2004-11-05'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f63', 'Home Alone', 'finished airing', 'Kevin McCallister yang berusia delapan tahun secara tidak sengaja tertinggal ketika keluarganya terbang ke Paris untuk liburan Natal. Awalnya menikmati kebebasannya, ia segera harus mempertahankan rumahnya dari dua perampok yang kikuk.', 103, 1, 'Chris Columbus', '1990-11-16'),
('f22abc99-9c0b-4ef8-bb6d-6bb9bd777f64', 'Rocky', 'finished airing', 'Rocky Balboa, seorang petinju kelas teri yang bekerja sebagai penagih utang, mendapat kesempatan sekali seumur hidup untuk melawan juara tinju kelas berat dunia, Apollo Creed, dalam sebuah pertandingan yang menjadi simbol semangat manusia.', 120, 1, 'John G. Avildsen', '1976-11-21');
